title: Ian Waudby-Smith 
url: "https://ianws.com"
baseurl: ""

markdown: kramdown

tracking_id: #

markdown: kramdown

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Papers"
   link: "papers"
 - name: "Software"
   link: "software"
 - name: "CV"
   link: "ianws_cv.pdf"
