title: Zhenghao(Tiger) Zeng
url: "tigerzhzeng.com"
baseurl: "Tiger-ZhenghaoZeng.github.io"

markdown: kramdown

tracking_id: #

markdown: kramdown

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Papers"
   link: "papers"
 - name: "CV"
   link: "Resume_Zhenghao.pdf"
