title: Ian Waudby-Smith 
url: "https://ianws.org
baseurl: ""

markdown: kramdown

tracking_id: G-4F3SPT3712

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "iws_cv.pdf"
